# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4737719adadd16e9e617d7af6665bdfbb1aa270cedd5b21395be7f38b60e0f169eb3ab1a6a0e929543151cc7619a1ee1b1e10da67e477a94be1b4752f17ae28f

test:
  secret_key_base: 2d4931dcdc5aaf0d0369860e66e231432716951d6e9033cb454309f6d93652f203ec329875d168eec634cdd0f94bb93e4ec14e6a7eaa984003c1a97ed118cbf3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
